### PR TITLE
Generate the bibliography from a BibTeX file

### PR DESCRIPTION
**Pull request by eviau-artefactual**
Goal: make it easier to generate the bibliography in a variety of styles by storing the information in a BibTeX format.

We could probably include the `pandoc` statements in a shell script to be run automatically everytime we add to the main `.bib` file... what do you think ?

Note that if we activate GitHub Pages on this repo, we could link to the HTML directly instead of having to go through the repo.

### CODE REVIEW

**Review by sevein — COMMENTED** [review]
Nice job!

> We could probably include the pandoc statements in a shell script to be run automatically everytime we add to the main .bib file... what do you think ?

Good idea. You could have the same script run in CI to check that the developers are including in the PR the updated generated documents.

A couple of questions:

- After taking a look at the md and html documents, I missed the categories we had by year. Can we list the entries by year with a custom pandoc template? Does it make sense to do it?
- Can we inject the generated Markdown into the current README instead to reproduce the current experience? It'd be nice to to reproduce the current user experience if possible. The build instructions could be maybe be part of a CONTRIBUTING.md file or similar.

**Comment by eviau-artefactual** [comment]
Now the CI works. Onto sorting by year - it should be possible.

**Comment by eviau-artefactual** [comment]
It seems like I was able to build the README.md from the files intro_placeholder.md and archivematica-bib.md - at least, the actions run. 

I am not sure how to test this without having to merge...

**Comment by eviau-artefactual** [comment]
> Now the CI works. Onto sorting by year - it should be possible.

This looks a bit more intricate than expected. Here are the options we have so far:

- use a [CSL](https://citationstyles.org/) with pandoc : the APA-CV style sorts by descending year, but after sorting by other criterion
- maintain a CSL that fits our needs
- sort in [pdflatex](https://tex.stackexchange.com/questions/551147/publication-list-ordered-by-year-using-biblatex?rq=1) we can sort by year - this gives us a PDF, not .md or .html pages

I will keep looking for options.

**Comment by eviau-artefactual** [comment]
Current expected workflow to add an entry to the archivematica.bib file:

- find an entry
- write a valid BibTeX reference for the entry
- git clone the repo
- add your entry somewhere in the archivematica.bib file, maybe at the top of it ?
- in a terminal window, navigate to the repo
- make a commit with your new entry
- from the root of the repo, run `./generate_bibs.sh`
- make a commit with the generated files.

I believe that committing generated files is not optimal practice, but this will have to do for now if we want to have the generated output published to the web...?

Questions for @sevein : 
- could we active Github pages so we could have a direct URL to the generated HTML bibliography ?
- if the workflow mentionned here works for you, I would add it to the CONTRIBUTING.md file

**Review by sevein — APPROVED** [review]
:+1:

**Pull request merged**
